// Decompiled with JetBrains decompiler
// Type: EdyCommonTools.GColor
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: F07798AD-7FDC-4402-AB44-D85C99F8E7B0
// Assembly location: C:\KSP2\DLL_stripped\Assembly-CSharp.dll
// XML documentation location: C:\KSP2\DLL_stripped\Assembly-CSharp.xml

using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace EdyCommonTools
{
  public class GColor
  {
    public static Color red;
    public static Color pink;
    public static Color purple;
    public static Color deepPurple;
    public static Color indigo;
    public static Color blue;
    public static Color lightBlue;
    public static Color cyan;
    public static Color teal;
    public static Color green;
    public static Color lightGreen;
    public static Color lime;
    public static Color yellow;
    public static Color amber;
    public static Color orange;
    public static Color deepOrange;
    public static Color brown;
    public static Color grey;
    public static Color blueGrey;
    public static Color solidRed;
    public static Color solidPink;
    public static Color solidPurple;
    public static Color solidDeepPurple;
    public static Color solidIndigo;
    public static Color solidBlue;
    public static Color solidLightBlue;
    public static Color solidCyan;
    public static Color solidTeal;
    public static Color solidGreen;
    public static Color solidLightGreen;
    public static Color solidLime;
    public static Color solidYellow;
    public static Color solidAmber;
    public static Color solidOrange;
    public static Color solidDeepOrange;
    public static Color solidBrown;
    public static Color solidGrey;
    public static Color solidBlueGrey;
    public static Color accentRed;
    public static Color accentPink;
    public static Color accentPurple;
    public static Color accentDeepPurple;
    public static Color accentIndigo;
    public static Color accentBlue;
    public static Color accentLightBlue;
    public static Color accentCyan;
    public static Color accentTeal;
    public static Color accentGreen;
    public static Color accentLightGreen;
    public static Color accentLime;
    public static Color accentYellow;
    public static Color accentAmber;
    public static Color accentOrange;
    public static Color accentDeepOrange;
    public static Color black;
    public static Color white;
    public static Color gray;
    public static Color red50;
    public static Color red100;
    public static Color red200;
    public static Color red300;
    public static Color red400;
    public static Color red500;
    public static Color red600;
    public static Color red700;
    public static Color red800;
    public static Color red900;
    public static Color pink50;
    public static Color pink100;
    public static Color pink200;
    public static Color pink300;
    public static Color pink400;
    public static Color pink500;
    public static Color pink600;
    public static Color pink700;
    public static Color pink800;
    public static Color pink900;
    public static Color purple50;
    public static Color purple100;
    public static Color purple200;
    public static Color purple300;
    public static Color purple400;
    public static Color purple500;
    public static Color purple600;
    public static Color purple700;
    public static Color purple800;
    public static Color purple900;
    public static Color deepPurple50;
    public static Color deepPurple100;
    public static Color deepPurple200;
    public static Color deepPurple300;
    public static Color deepPurple400;
    public static Color deepPurple500;
    public static Color deepPurple600;
    public static Color deepPurple700;
    public static Color deepPurple800;
    public static Color deepPurple900;
    public static Color indigo50;
    public static Color indigo100;
    public static Color indigo200;
    public static Color indigo300;
    public static Color indigo400;
    public static Color indigo500;
    public static Color indigo600;
    public static Color indigo700;
    public static Color indigo800;
    public static Color indigo900;
    public static Color blue50;
    public static Color blue100;
    public static Color blue200;
    public static Color blue300;
    public static Color blue400;
    public static Color blue500;
    public static Color blue600;
    public static Color blue700;
    public static Color blue800;
    public static Color blue900;
    public static Color lightBlue50;
    public static Color lightBlue100;
    public static Color lightBlue200;
    public static Color lightBlue300;
    public static Color lightBlue400;
    public static Color lightBlue500;
    public static Color lightBlue600;
    public static Color lightBlue700;
    public static Color lightBlue800;
    public static Color lightBlue900;
    public static Color cyan50;
    public static Color cyan100;
    public static Color cyan200;
    public static Color cyan300;
    public static Color cyan400;
    public static Color cyan500;
    public static Color cyan600;
    public static Color cyan700;
    public static Color cyan800;
    public static Color cyan900;
    public static Color teal50;
    public static Color teal100;
    public static Color teal200;
    public static Color teal300;
    public static Color teal400;
    public static Color teal500;
    public static Color teal600;
    public static Color teal700;
    public static Color teal800;
    public static Color teal900;
    public static Color green50;
    public static Color green100;
    public static Color green200;
    public static Color green300;
    public static Color green400;
    public static Color green500;
    public static Color green600;
    public static Color green700;
    public static Color green800;
    public static Color green900;
    public static Color lightGreen50;
    public static Color lightGreen100;
    public static Color lightGreen200;
    public static Color lightGreen300;
    public static Color lightGreen400;
    public static Color lightGreen500;
    public static Color lightGreen600;
    public static Color lightGreen700;
    public static Color lightGreen800;
    public static Color lightGreen900;
    public static Color lime50;
    public static Color lime100;
    public static Color lime200;
    public static Color lime300;
    public static Color lime400;
    public static Color lime500;
    public static Color lime600;
    public static Color lime700;
    public static Color lime800;
    public static Color lime900;
    public static Color yellow50;
    public static Color yellow100;
    public static Color yellow200;
    public static Color yellow300;
    public static Color yellow400;
    public static Color yellow500;
    public static Color yellow600;
    public static Color yellow700;
    public static Color yellow800;
    public static Color yellow900;
    public static Color amber50;
    public static Color amber100;
    public static Color amber200;
    public static Color amber300;
    public static Color amber400;
    public static Color amber500;
    public static Color amber600;
    public static Color amber700;
    public static Color amber800;
    public static Color amber900;
    public static Color orange50;
    public static Color orange100;
    public static Color orange200;
    public static Color orange300;
    public static Color orange400;
    public static Color orange500;
    public static Color orange600;
    public static Color orange700;
    public static Color orange800;
    public static Color orange900;
    public static Color deepOrange50;
    public static Color deepOrange100;
    public static Color deepOrange200;
    public static Color deepOrange300;
    public static Color deepOrange400;
    public static Color deepOrange500;
    public static Color deepOrange600;
    public static Color deepOrange700;
    public static Color deepOrange800;
    public static Color deepOrange900;
    public static Color brown50;
    public static Color brown100;
    public static Color brown200;
    public static Color brown300;
    public static Color brown400;
    public static Color brown500;
    public static Color brown600;
    public static Color brown700;
    public static Color brown800;
    public static Color brown900;
    public static Color grey50;
    public static Color grey100;
    public static Color grey200;
    public static Color grey300;
    public static Color grey400;
    public static Color grey500;
    public static Color grey600;
    public static Color grey700;
    public static Color grey800;
    public static Color grey900;
    public static Color blueGrey50;
    public static Color blueGrey100;
    public static Color blueGrey200;
    public static Color blueGrey300;
    public static Color blueGrey400;
    public static Color blueGrey500;
    public static Color blueGrey600;
    public static Color blueGrey700;
    public static Color blueGrey800;
    public static Color blueGrey900;
    public static Color redA100;
    public static Color redA200;
    public static Color redA400;
    public static Color redA700;
    public static Color pinkA100;
    public static Color pinkA200;
    public static Color pinkA400;
    public static Color pinkA700;
    public static Color purpleA100;
    public static Color purpleA200;
    public static Color purpleA400;
    public static Color purpleA700;
    public static Color deepPurpleA100;
    public static Color deepPurpleA200;
    public static Color deepPurpleA400;
    public static Color deepPurpleA700;
    public static Color indigoA100;
    public static Color indigoA200;
    public static Color indigoA400;
    public static Color indigoA700;
    public static Color blueA100;
    public static Color blueA200;
    public static Color blueA400;
    public static Color blueA700;
    public static Color lightBlueA100;
    public static Color lightBlueA200;
    public static Color lightBlueA400;
    public static Color lightBlueA700;
    public static Color cyanA100;
    public static Color cyanA200;
    public static Color cyanA400;
    public static Color cyanA700;
    public static Color tealA100;
    public static Color tealA200;
    public static Color tealA400;
    public static Color tealA700;
    public static Color greenA100;
    public static Color greenA200;
    public static Color greenA400;
    public static Color greenA700;
    public static Color lightGreenA100;
    public static Color lightGreenA200;
    public static Color lightGreenA400;
    public static Color lightGreenA700;
    public static Color limeA100;
    public static Color limeA200;
    public static Color limeA400;
    public static Color limeA700;
    public static Color yellowA100;
    public static Color yellowA200;
    public static Color yellowA400;
    public static Color yellowA700;
    public static Color amberA100;
    public static Color amberA200;
    public static Color amberA400;
    public static Color amberA700;
    public static Color orangeA100;
    public static Color orangeA200;
    public static Color orangeA400;
    public static Color orangeA700;
    public static Color deepOrangeA100;
    public static Color deepOrangeA200;
    public static Color deepOrangeA400;
    public static Color deepOrangeA700;
    private static Dictionary<string, Color> m_colors;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static Color Alpha(Color col, float alpha) => throw null;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static Color ParseColor(string col) => throw null;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static Color ParseColorHex(string col) => throw null;

    [MethodImpl(MethodImplOptions.NoInlining)]
    static GColor() => throw null;

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static int HexToDecimal(char ch) => throw null;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public GColor() => throw null;
  }
}
