// Decompiled with JetBrains decompiler
// Type: KSP.Modules.ResourceConverterFormulaDefinition
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EF61A348-EB87-4C99-B6BD-CBCF875CC384
// Assembly location: C:\KSP2\DLL_min\Assembly-CSharp.dll
// XML documentation location: C:\KSP2\DLL_min\Assembly-CSharp.xml

using KSP.Sim.Definitions;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace KSP.Modules
{
  [Serializable]
  public class ResourceConverterFormulaDefinition
  {
    [Tooltip("A unique name to identify the formula internally")]
    public string InternalName;
    [Tooltip("A localization string that is the formula name")]
    public string FormulaLocalizationKey;
    [Tooltip("An output resource list which denotes input resource names and rates in units/second")]
    public List<PartModuleResourceSetting> InputResources;
    [Tooltip("An output resource list which denotes input resource names and rates in units/second")]
    public List<PartModuleResourceSetting> OutputResources;
    [Tooltip("The amount of heat flux generated by this formula in kW")]
    public float FluxGenerated;
    [Tooltip("The minimum resource value for resource requests")]
    public double AcceptanceThreshold;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public ResourceConverterFormulaDefinition() => throw null;
  }
}
